#!/usr/bin/env python3
"""Generate the build/version note included at the end of a review PDF.

Writes a small .qmd fragment recording the generation date, the current
git commit (or a "pre-commit" marker if the tree has uncommitted
changes touching the workbook), and a fixed pilot-status line. Run this
immediately before rendering a review build -- never hand-edit the
generated file, since it will be silently overwritten.

Usage:
    python3 scripts/generate_build_note.py \\
        --output workbooks/04-llm-architecture/includes/build-version-note.qmd \\
        --pilot-status "Two-chapter pilot (Chapters 1-2 of 8)" \\
        --registry-note "sources/registry.yaml src-19/22/23/24 last verified 2026-09-22" \\
        --provenance-note "Tied-embeddings usage has no dedicated primary source; sandwich-norm leans on a secondary source." \\
        --provenance-note "Worked-example numbers (attention weights, parameter counts) are computed by version-controlled project scripts and checked by the project's automated test suite, not hand-derived."
"""
import argparse
import datetime
import os
import subprocess


def git_commit_or_precommit(repo_root: str) -> str:
    status = subprocess.run(["git", "status", "--porcelain"], cwd=repo_root, capture_output=True, text=True)
    dirty = bool(status.stdout.strip())
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=repo_root, capture_output=True, text=True)
    sha = head.stdout.strip()
    if dirty:
        return f"{sha} (pre-commit -- working tree had uncommitted changes at build time)"
    return sha


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--pilot-status", required=True)
    parser.add_argument("--registry-note", required=True)
    parser.add_argument("--provenance-note", action="append", default=[],
                         help="One bullet for the Provenance subsection; may be repeated.")
    args = parser.parse_args()

    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    commit = git_commit_or_precommit(repo_root)
    today = datetime.date.today().isoformat()

    provenance_bullets = "\n".join(f"- {note}" for note in args.provenance_note)

    content = f"""## Build and Version Note

- **Generated:** {today}
- **Git commit:** `{commit}`
- **Source-registry verification date referenced by this build:** {args.registry_note}
- **Pilot status:** {args.pilot_status}

### Provenance

{provenance_bullets}

This note is generated by `scripts/generate_build_note.py` at build
time -- do not hand-edit `includes/build-version-note.qmd`; regenerate
it instead.
"""
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(content)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
